
package com.xmlme.news;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-16T09:57:23.598-06:00
 * Generated source version: 2.5.0
 * 
 */
public final class GetCustomNewsSoap_GetCustomNewsSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlme.com/WebServices", "GetCustomNews");

    private GetCustomNewsSoap_GetCustomNewsSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GetCustomNews_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetCustomNews_Service ss = new GetCustomNews_Service(wsdlURL, SERVICE_NAME);
        GetCustomNewsSoap port = ss.getGetCustomNewsSoap12();  
        
        {
        System.out.println("Invoking getCustomNews...");
        java.lang.String _getCustomNews_topic = "";
        java.lang.String _getCustomNews__return = port.getCustomNews(_getCustomNews_topic);
        System.out.println("getCustomNews.result=" + _getCustomNews__return);


        }

        System.exit(0);
    }

}
