package com.xmlme.news;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-16T09:57:23.631-06:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "GetCustomNews", 
                  wsdlLocation = "http://www.xmlme.com/WSCustNews.asmx?WSDL",
                  targetNamespace = "http://xmlme.com/WebServices") 
public class GetCustomNews_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlme.com/WebServices", "GetCustomNews");
    public final static QName GetCustomNewsSoap = new QName("http://xmlme.com/WebServices", "GetCustomNewsSoap");
    public final static QName GetCustomNewsSoap12 = new QName("http://xmlme.com/WebServices", "GetCustomNewsSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://www.xmlme.com/WSCustNews.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetCustomNews_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.xmlme.com/WSCustNews.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public GetCustomNews_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetCustomNews_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetCustomNews_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GetCustomNewsSoap
     */
    @WebEndpoint(name = "GetCustomNewsSoap")
    public GetCustomNewsSoap getGetCustomNewsSoap() {
        return super.getPort(GetCustomNewsSoap, GetCustomNewsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCustomNewsSoap
     */
    @WebEndpoint(name = "GetCustomNewsSoap")
    public GetCustomNewsSoap getGetCustomNewsSoap(WebServiceFeature... features) {
        return super.getPort(GetCustomNewsSoap, GetCustomNewsSoap.class, features);
    }
    /**
     *
     * @return
     *     returns GetCustomNewsSoap
     */
    @WebEndpoint(name = "GetCustomNewsSoap12")
    public GetCustomNewsSoap getGetCustomNewsSoap12() {
        return super.getPort(GetCustomNewsSoap12, GetCustomNewsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCustomNewsSoap
     */
    @WebEndpoint(name = "GetCustomNewsSoap12")
    public GetCustomNewsSoap getGetCustomNewsSoap12(WebServiceFeature... features) {
        return super.getPort(GetCustomNewsSoap12, GetCustomNewsSoap.class, features);
    }

}
