package com.xmlme.news;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-16T09:57:23.618-06:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://xmlme.com/WebServices", name = "GetCustomNewsSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface GetCustomNewsSoap {

    /**
     * Submit a News Topic and a List of Articles will be returned in XML from the Moreover News Service.
     */
    @WebResult(name = "GetCustomNewsResult", targetNamespace = "http://xmlme.com/WebServices")
    @RequestWrapper(localName = "GetCustomNews", targetNamespace = "http://xmlme.com/WebServices", className = "com.xmlme.news.GetCustomNews")
    @WebMethod(operationName = "GetCustomNews", action = "http://xmlme.com/WebServices/GetCustomNews")
    @ResponseWrapper(localName = "GetCustomNewsResponse", targetNamespace = "http://xmlme.com/WebServices", className = "com.xmlme.news.GetCustomNewsResponse")
    public java.lang.String getCustomNews(
        @WebParam(name = "Topic", targetNamespace = "http://xmlme.com/WebServices")
        java.lang.String topic
    );
}
