
package com.sexingtechnologies.b1ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-17T14:21:40.929-06:00
 * Generated source version: 2.5.0
 * 
 */
public final class LoginServiceSoap_LoginServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("LoginService", "LoginService");

    private LoginServiceSoap_LoginServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LoginService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LoginService ss = new LoginService(wsdlURL, SERVICE_NAME);
        LoginServiceSoap port = ss.getLoginServiceSoap();  
        
        {
        System.out.println("Invoking logout...");
        com.sexingtechnologies.b1ws.Logout _logout_parameters = null;
        com.sexingtechnologies.b1ws.MsgHeader _logout_requestHeader = null;
        com.sexingtechnologies.b1ws.LogoutResponse _logout__return = port.logout(_logout_parameters, _logout_requestHeader);
        System.out.println("logout.result=" + _logout__return);


        }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_databaseServer = "";
        java.lang.String _login_databaseName = "";
        java.lang.String _login_databaseType = "";
        java.lang.String _login_databaseUserName = "";
        java.lang.String _login_databasePassword = "";
        java.lang.String _login_companyUsername = "";
        java.lang.String _login_companyPassword = "";
        java.lang.String _login_language = "";
        java.lang.String _login_licenseServer = "";
        java.lang.String _login__return = port.login(_login_databaseServer, _login_databaseName, _login_databaseType, _login_databaseUserName, _login_databasePassword, _login_companyUsername, _login_companyPassword, _login_language, _login_licenseServer);
        System.out.println("login.result=" + _login__return);


        }

        System.exit(0);
    }

}
