package com.sexingtechnologies.b1ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-17T14:21:41.056-06:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "LoginService", name = "LoginServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface LoginServiceSoap {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "LogoutResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    @WebMethod(operationName = "Logout", action = "LoginService/Logout")
    public LogoutResponse logout(
        @WebParam(partName = "parameters", name = "Logout", targetNamespace = "LoginService")
        Logout parameters,
        @WebParam(partName = "request_header", name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true)
        MsgHeader requestHeader
    );

    @WebResult(name = "SessionID", targetNamespace = "http://www.sap.com/SBO/DIS")
    @RequestWrapper(localName = "Login", targetNamespace = "LoginService", className = "com.sexingtechnologies.b1ws.Login")
    @WebMethod(operationName = "Login", action = "LoginService/Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://www.sap.com/SBO/DIS", className = "com.sexingtechnologies.b1ws.LoginResponse")
    public java.lang.String login(
        @WebParam(name = "DatabaseServer", targetNamespace = "LoginService")
        java.lang.String databaseServer,
        @WebParam(name = "DatabaseName", targetNamespace = "LoginService")
        java.lang.String databaseName,
        @WebParam(name = "DatabaseType", targetNamespace = "LoginService")
        java.lang.String databaseType,
        @WebParam(name = "DatabaseUserName", targetNamespace = "LoginService")
        java.lang.String databaseUserName,
        @WebParam(name = "DatabasePassword", targetNamespace = "LoginService")
        java.lang.String databasePassword,
        @WebParam(name = "CompanyUsername", targetNamespace = "LoginService")
        java.lang.String companyUsername,
        @WebParam(name = "CompanyPassword", targetNamespace = "LoginService")
        java.lang.String companyPassword,
        @WebParam(name = "Language", targetNamespace = "LoginService")
        java.lang.String language,
        @WebParam(name = "LicenseServer", targetNamespace = "LoginService")
        java.lang.String licenseServer
    );
}
