package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-21T20:15:49.503-06:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    public java.lang.String helloWorld();

    @WebResult(name = "GetDataTableResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDataTable", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataTable")
    @WebMethod(operationName = "GetDataTable", action = "http://tempuri.org/GetDataTable")
    @ResponseWrapper(localName = "GetDataTableResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataTableResponse")
    public org.tempuri.GetDataTableResponse.GetDataTableResult getDataTable(
        @WebParam(name = "SQL", targetNamespace = "http://tempuri.org/")
        java.lang.String sql
    );

    @WebResult(name = "IsAliveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsAlive", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsAlive")
    @WebMethod(operationName = "IsAlive", action = "http://tempuri.org/IsAlive")
    @ResponseWrapper(localName = "IsAliveResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsAliveResponse")
    public boolean isAlive();

    @WebResult(name = "AddBPResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddBP", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddBP")
    @WebMethod(operationName = "AddBP", action = "http://tempuri.org/AddBP")
    @ResponseWrapper(localName = "AddBPResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddBPResponse")
    public boolean addBP(
        @WebParam(name = "BP", targetNamespace = "http://tempuri.org/")
        org.tempuri.BusinessPartner bp
    );

    @WebResult(name = "ConnectedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Connected", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Connected")
    @WebMethod(operationName = "Connected", action = "http://tempuri.org/Connected")
    @ResponseWrapper(localName = "ConnectedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConnectedResponse")
    public boolean connected();
}
