package uk.co.demon;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-15T15:57:43.616-06:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://nsi-ltd.demon.co.uk/axis/services/DigDNS", name = "DigDNS")
@XmlSeeAlso({ObjectFactory.class})
public interface DigDNS {

    @WebResult(name = "getRecordTypesReturn", targetNamespace = "http://DefaultNamespace")
    @RequestWrapper(localName = "getRecordTypes", targetNamespace = "http://DefaultNamespace", className = "uk.co.demon.GetRecordTypes")
    @WebMethod
    @ResponseWrapper(localName = "getRecordTypesResponse", targetNamespace = "http://DefaultNamespace", className = "uk.co.demon.GetRecordTypesResponse")
    public java.util.List<java.lang.String> getRecordTypes();

    @WebResult(name = "getNameserverReturn", targetNamespace = "http://DefaultNamespace")
    @RequestWrapper(localName = "getNameserver", targetNamespace = "http://DefaultNamespace", className = "uk.co.demon.GetNameserver")
    @WebMethod
    @ResponseWrapper(localName = "getNameserverResponse", targetNamespace = "http://DefaultNamespace", className = "uk.co.demon.GetNameserverResponse")
    public java.lang.String getNameserver(
        @WebParam(name = "index", targetNamespace = "http://DefaultNamespace")
        int index
    );

    @WebResult(name = "getQueryStringReturn", targetNamespace = "http://DefaultNamespace")
    @RequestWrapper(localName = "getQueryString", targetNamespace = "http://DefaultNamespace", className = "uk.co.demon.GetQueryString")
    @WebMethod
    @ResponseWrapper(localName = "getQueryStringResponse", targetNamespace = "http://DefaultNamespace", className = "uk.co.demon.GetQueryStringResponse")
    public uk.co.demon.Vector getQueryString(
        @WebParam(name = "sTarget", targetNamespace = "http://DefaultNamespace")
        java.lang.String sTarget,
        @WebParam(name = "index", targetNamespace = "http://DefaultNamespace")
        int index,
        @WebParam(name = "sType", targetNamespace = "http://DefaultNamespace")
        java.lang.String sType
    );

    @WebResult(name = "getNumberOfNameserversReturn", targetNamespace = "http://DefaultNamespace")
    @RequestWrapper(localName = "getNumberOfNameservers", targetNamespace = "http://DefaultNamespace", className = "uk.co.demon.GetNumberOfNameservers")
    @WebMethod
    @ResponseWrapper(localName = "getNumberOfNameserversResponse", targetNamespace = "http://DefaultNamespace", className = "uk.co.demon.GetNumberOfNameserversResponse")
    public int getNumberOfNameservers();
}
