package uk.co.demon;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-15T15:57:43.634-06:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "DigDNSService", 
                  wsdlLocation = "http://nsi-ltd.demon.co.uk/axis/services/DigDNS?wsdl",
                  targetNamespace = "http://nsi-ltd.demon.co.uk/axis/services/DigDNS") 
public class DigDNSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://nsi-ltd.demon.co.uk/axis/services/DigDNS", "DigDNSService");
    public final static QName DigDNS = new QName("http://nsi-ltd.demon.co.uk/axis/services/DigDNS", "DigDNS");
    static {
        URL url = null;
        try {
            url = new URL("http://nsi-ltd.demon.co.uk/axis/services/DigDNS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DigDNSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://nsi-ltd.demon.co.uk/axis/services/DigDNS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DigDNSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DigDNSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DigDNSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DigDNS
     */
    @WebEndpoint(name = "DigDNS")
    public DigDNS getDigDNS() {
        return super.getPort(DigDNS, DigDNS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DigDNS
     */
    @WebEndpoint(name = "DigDNS")
    public DigDNS getDigDNS(WebServiceFeature... features) {
        return super.getPort(DigDNS, DigDNS.class, features);
    }

}
