
package uk.co.demon;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-15T15:57:43.478-06:00
 * Generated source version: 2.5.0
 * 
 */
public final class DigDNS_DigDNS_Client {

    private static final QName SERVICE_NAME = new QName("http://nsi-ltd.demon.co.uk/axis/services/DigDNS", "DigDNSService");

    private DigDNS_DigDNS_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DigDNSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DigDNSService ss = new DigDNSService(wsdlURL, SERVICE_NAME);
        DigDNS port = ss.getDigDNS();  
        
        {
        System.out.println("Invoking getRecordTypes...");
        java.util.List<java.lang.String> _getRecordTypes__return = port.getRecordTypes();
        System.out.println("getRecordTypes.result=" + _getRecordTypes__return);


        }
        {
        System.out.println("Invoking getNameserver...");
        int _getNameserver_index = 0;
        java.lang.String _getNameserver__return = port.getNameserver(_getNameserver_index);
        System.out.println("getNameserver.result=" + _getNameserver__return);


        }
        {
        System.out.println("Invoking getQueryString...");
        java.lang.String _getQueryString_sTarget = "";
        int _getQueryString_index = 0;
        java.lang.String _getQueryString_sType = "";
        uk.co.demon.Vector _getQueryString__return = port.getQueryString(_getQueryString_sTarget, _getQueryString_index, _getQueryString_sType);
        System.out.println("getQueryString.result=" + _getQueryString__return);


        }
        {
        System.out.println("Invoking getNumberOfNameservers...");
        int _getNumberOfNameservers__return = port.getNumberOfNameservers();
        System.out.println("getNumberOfNameservers.result=" + _getNumberOfNameservers__return);


        }

        System.exit(0);
    }

}
